
(documentation ">doc>sm>sysin_mode.doc")

(variable current_buffer current_filename)
(variable keep_on_tunneling)
(variable beginning_of_line)
(static sysin_eol)
(static sysin_operator_column)
(static sysin_operand_column)
(static sysin_comment_column)
(static tg1)
(static White&CR)
(variable M_dispatch)
(variable argument argumentp)
(variable save_buffer)

(defun user_init()
       (store (make_gnirt) tg1)
       (store (fill_char_array (make_array 1 128) "    
") White&CR)
       (store 10 sysin_operator_column)
       (store 20 sysin_operand_column)
       (store 30 sysin_comment_column))

(defun sysin_mode ()
       (sysin_scan_options)
       (bind_key C-M-I sysin_indent_line)
       (bind_key C-M-Z compile_sysin)
       (keep_on_tunneling))

(defun compile_sysin()
       (save_buffer)
       (delete tg1 99999)
       (insert "midi " tg1)
       (insert current_filename tg1)
       (delete tg1 6)
       (cline tg1))

(defun sysin_scan_options(&aux number char old)
       (store (location current_buffer) old)
       (set_loc current_buffer 0)
       (set_loc current_buffer (iferror (search current_buffer "* options:: ")
                                        (goto noopt)))
       (store 0 number)
loop   (store (nthr current_buffer 0) char)
       (cond ((and (gep char "0") (lep char "9"))
              (store (add (mul number 10) (and char 15)) number))
             ((eq char "^")
              (store 1 number))
             ((eq char "o")
              (store number sysin_operator_column)
              (store 0 number))
             ((eq char "r")
              (store number sysin_operand_column)
              (store 0 number))
             ((eq char "c")
              (store number sysin_comment_column)
              (store 0 number))
             ((t)
noopt         (set_loc current_buffer old)
              (return)))
       (add_to_loc current_buffer 1)
       (goto loop))



(defun goto_column(there &aux here)
       (store (sub (get_hpos current_buffer (location current_buffer)) 1) here)
       (ift (gep here there) punt)
attab  (ifnil (gp (sub there here) 4) finis)
       (insert 9 current_buffer)
       (store (add here 5) here)
       (store (sub here (mod here 5)) here)
       (goto attab)
finis  (ift (eq here there) punt)
       (insert 32 current_buffer)
       (store (add here 1) here)
       (goto finis)
punt   )

(defun goto_column_w(there)
       (delete_white_right)
       (ift (and sysin_eol argumentp) punt)
       (goto_column there)
       (ift (eq (ar White&CR (nthr current_buffer -1)) 1) punt)
       (insert 9 current_buffer)
punt   )

(defun delete_white_right(&aux oldpos)
       (store (location current_buffer) oldpos)
       (set_loc current_buffer (find_first_not_in_fa current_buffer "      "))
       (delete current_buffer (sub oldpos (location current_buffer)))
       (store (eq (nthr current_buffer 0) 13) sysin_eol))

(defun sysin_indent_line(&aux char column)
       (beginning_of_line)
loop   (store (nthr current_buffer 0) char)
       (ift (eq char "*") punt)
       (ift (or (eq char " ") (or (eq char 9) (eq char 13))) label)

       (set_loc current_buffer (find_first_in_fa current_buffer White&CR))

label  (goto_column_w sysin_operator_column)
       (ift sysin_eol punt)

       (set_loc current_buffer (find_first_in_fa current_buffer White&CR))
       (goto_column_w sysin_operand_column)
       (ift sysin_eol punt)

       (set_loc current_buffer (find_first_in_fa current_buffer White&CR))
       (goto_column_w sysin_comment_column)

punt   (ift (lep argument 1) retn)
       (set_loc current_buffer (iferror (search current_buffer 13)
                                        (goto retn)))
       (store (sub argument 1) argument)
       (goto loop)
retn  )
^L